 Desarrollar un código en Jupyter Notebook que trabaje con arrays y realice varias operaciones
matemáticas y de manipulación de datos. El programa debe obtener la mediana, el promedio, y las
posiciones de los valores máximo y mínimo de un array. Además, deberá transformar el array en una
matriz y utilizar las funciones específicas para ello. A continuación se detalla los requerimientos:
(50 Pts)
A. Crear un array de 10 elementos. Los elementos de este array deben ser consecutivos
del 1 al 10. Este array no debe ser aleatorio.
B. Crear un segundo array de 10 elementos. Este array si debe ser aleatorio. Los valores
deben ser enteros entre el 1 al 20.
C. Obtener un vector único de 10 elementos, sumando los dos arrays anteriores.
D. Mezclar el vector obtenido en la letra C utilizando una función vista en la Unidad IV.
E. Calcular la Mediana, el Promedio y Posiciones de Valores Máximo y Mínimo utilizando
las funciones vistas en la Unidad IV. Tomar el vector de la letra D.
E. Transformar el vector obtenido en una Matriz de 2 x 5

In [4]:
import numpy as np
import random
import matplotlib.pyplot as plt

In [8]:
array= np.array([1,2,3,4,5,6,7,8,9,10])
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
array2=[]
for i in range(10):
  n= np.random.randint(1,21)
  array2.append(n)
array2 = np.array(array2)
array2

array([19,  7,  2, 19, 19, 17,  3, 16, 18, 12])

In [20]:
vector= array + array2
vector

array([20,  9,  5, 23, 24, 23, 10, 24, 27, 22])

No supe hacer la D, asi que lo hago con la suma de los array sin mezclar:

In [26]:
vector_mediana= np.median(vector)
vector_prom= np.mean(vector)
max= np.argmax(vector)
min= np.argmin(vector)


In [27]:
matriz= np.reshape(vector,(2,5))
matriz

array([[20,  9,  5, 23, 24],
       [23, 10, 24, 27, 22]])